version: "3.8"
services:

    nginx:
        image: nginx:alpine
        container_name: bdgt_nginx
        volumes:
            - .:/var/www/html/
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
        restart: unless-stopped

    mysql:
        image: mysql
        container_name: bdgt_mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: bdgt
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: bdgt
        ports:
            - 3306:3306
        volumes:
            - mysql-volume:/var/lib/mysql
        depends_on:
            - php
        restart: unless-stopped

    php:
      build: ./docker/php
      container_name: bdgt_php
      volumes:
          - .:/var/www/html
      restart: unless-stopped

volumes:
  mysql-volume:
