name: Run tests

on: push

jobs:
    php-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Copy .env file
              run: cp .env.example .env

            - name: Install Composer dependencies
              run: composer install --no-interaction --no-suggest --no-progress --prefer-dist

            - name: Generate app key
              run: php artisan key:generate

            - name: Run PHPUnit tests
              run: php vendor/bin/phpunit
